

export const FILE_LIST = [
  "KERNEL.EXE", "DOS4GW.EXE", "C&C.EXE", "SETUP.EXE", "UNINSTALL.EXE",
  "GDI.MIX", "NOD.MIX", "SCORES.MIX", "LOCAL.MIX", "TEMPERAT.MIX",
  "SNOW.MIX", "DESERT.MIX", "JUNGLE.MIX", "URBAN.MIX", "WINTER.MIX",
  "SOUNDS.DAT", "SPEECH.DAT", "MUSIC.DAT", "INTRO.VQA", "FINALE.VQA",
  "MAP01.BIN", "MAP01.INI", "MAP02.BIN", "MAP02.INI", "MAP03.BIN",
  "GDI_A01.VQA", "NOD_A01.VQA", "COMM.DAT", "TRANS.TBL", "PALETTE.PAL",
  "MOUSE.DRV", "VIDEO.DRV", "SB16.DRV", "AWE32.DRV", "GUS.DRV",
  "TITLES.PCX", "MAINMENU.PCX", "SIDEBAR.SHP", "BUILD.SHP", "UNIT.SHP",
  "HUMVEE.SHP", "APC.SHP", "TANK_LT.SHP", "TANK_MED.SHP", "TANK_HVY.SHP",
  "MAMMOUTH.SHP", "ORCA.SHP", "HELI.SHP", "SAM.SHP", "TURRET.SHP",
  "CONST.SHP", "REFINERY.SHP", "SILO.SHP", "POWER.SHP", "ADV_PWR.SHP",
  "BARRACKS.SHP", "HAND.SHP", "COM_CNTR.SHP", "ADV_COM.SHP", "REPAIR.SHP"
];

export const SYSTEM_SPECS = [
  { label: "PROCESSOR", value: "INTEL 80486DX2-66" },
  { label: "MEMORY", value: "16384 KB OK" },
  { label: "VIDEO", value: "VGA ADAPTER DETECTED" },
  { label: "DOS VERSION", value: "6.22" },
  { label: "MOUSE", value: "MICROSOFT COMPATIBLE" },
];

export enum InstallStep {
  BOOT_SEQUENCE, // New Step 1
  SERIAL_INPUT,  // New Step 2
  WELCOME,
  TRANSMISSION,
  LICENSE_AGREEMENT,
  FACTION_SELECT,
  IDENTITY_AUTH,
  DESTINATION,
  SYSTEM_CHECK,
  SOUND_CONFIG,
  DATA_UPLINK,
  COPYING,
  INSTALL_SUCCESS,
  INTRO_SEQUENCE,
  COMPLETE,
  SHUTDOWN
}
